## **What is NumPy?**

NumPy, which stands for Numerical Python is a Python library used to represent, store, and manipulate massive datasets efficiently through a data structure called the N dimentional array. Almost every ML library uses NumPy internally.

NumPy gives us
- Faster calculations
- Multi-dimensional arrays
- Mathematical functions
- Linear algebra operations

In [1]:
import numpy as np

In [ ]:
marks = np.array([85,90,78,92,88])
print(marks)

[85 90 78 92 88]


In [ ]:
# Statistics of the array
print("Mean: ",marks.mean()) # Average marks
print("Max: ",marks.max()) # Highest marks
print("Min: ",marks.min()) # Lowest marks

86.6
92
78


In [50]:
# Shape of the array
matrix = np.array([1,2,3,4,5])
print("Matrix: ",matrix)
print("Shape: ",matrix.shape)  # This will return the shape of the array (rows, columns)
print(" This means 5 elements, 1 dimensional array")
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Matrix2: \n",matrix)
print("Shape2: ",matrix.shape)

Matrix:  [1 2 3 4 5]
Shape:  (5,)
 This means 5 elements, 1 dimensional array
Matrix2: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape2:  (3, 3)


In [18]:
# Indexing
numbers = np.array([10,20,30,40,50])
print("Number at index 3: ",numbers[3])

Number at index 3:  40


In [21]:
# Slicing (array[start:end])
print("Numbers from index 1 to 3: ",numbers[1:4]) # Start is inclusive and end is exclusive

Numbers from index 1 to 3:  [20 30 40]


In [30]:
print("Array of Zeroes: ",np.zeros(5)) # Create an array of zeros with 5 elements
print("Array of Ones: ",np.ones(5)) # Create an array of ones with 5 elements

Array of Zeroes:  [0. 0. 0. 0. 0.]
Array of Ones:  [1. 1. 1. 1. 1.]


In [32]:
# Range
# Instead of having to type out all the numbers, we can use np.arange to create an array of numbers in a specified range.
print("Array from 0 to 5: ", np.arange(0,6)) # Create an array of numbers from 0 to 6 (exclusive of 7)

Array from 0 to 5:  [0 1 2 3 4 5]


In [35]:
# Basic Math
a = np.array([10,20,30])
b = np.array([1,2,3])
print("Sum: ", a+b)
print("Product: ", a*b)
# This is called vectorised operations, where the operation is applied element-wise to the arrays.


Sum:  [11 22 33]
Product:  [10 40 90]


In [48]:
# Random numbers
np.random.rand(5) # Create an array of 5 random floating point numbers between 0 and 1
print("Random numbers: ", np.random.rand(5))
print("Random integers: ", np.random.randint(1,10,5)) # Create an array of 5 random integers between 1 and 10 (exclusive of 10)

Random numbers:  [0.86646275 0.61367802 0.31038394 0.20395007 0.15858138]
Random integers:  [6 3 9 8 7]


In [49]:
# Mini Challenge
# Create a NumPy array containing marks of 10 students.
# Calculate avg, highest, lowest, how many students scored above 80

marks = np.array([20,50,30,90,67,98,100])
print("Avg marks: ", marks.mean())
print("Highest marks: ", marks.max())
print("Lowest marks:", marks.min())
print("Number of students scored above 80: ", np.sum(marks > 80))

Avg marks:  65.0
Highest marks:  100
Lowest marks: 20
Number of students scored above 80:  3
